network_access = true

[features]
web_search_request = true

# MCP
[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex", "--enable-web-dashboard=false", "--project", "$(pwd)"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]
